### ISSUE TITLE
Badge (new component)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#103]
### Design update 2020-01-13

**What is this?**
This component calls attention to a status/tag/category.
![image](https://user-images.githubusercontent.com/45568194/72283689-95114d00-363f-11ea-952d-556b86833a3e.png)

**Details**
See the specification to get all the right details:
https://designlibrary.sebgroup.com/components/badge/

**Component identifier**
component-badge

Thank you!
/Ulrika

**Comment by yousifalraheem** [comment]
@ulde01 
I don't think this component needs a React or Angular component since it's not interactive. You can easily render this using
```html
<span class="badge badge-danger"></span>
```
If there is a design change, then it should just be implemented in **@sebgroup/bootstrap**.
