### ISSUE TITLE
Change name of Alternative button to Button link

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#110]
### Change
The button **Button link** used to be called Alternative button.
![image](https://user-images.githubusercontent.com/45568194/73255582-abcbae00-41c0-11ea-847c-77eba28105a8.png)
### Reason
The name Button link says what it is.

See the full specification here: 
https://designlibrary.sebgroup.com/components/forms/button/

Feel free to update this in your frameworks so that we use the same language on components. If this is not relevant to you, please close the issue with a comment. Thank you!

/Ulrika,
Design Management team

**Comment by yousifalraheem** [comment]
The `alternative` theme is actually the `secondary` bootstrap button theme since the `secondary` uses `outline-primary`. However, we have link in our themes and it's called `anchor`. Maybe we can rename this to `link`.

**Comment by hjalmers** [comment]
Since you use bootstrap you should be able to use `btn-link` as the modifier for a button in this case i.e. `btn btn-link`:)
