### ISSUE TITLE
Logo on top left went missing on develop branch

### ISSUE THREAD

**Issue by kherP** [sebgroup/react-components#145]
**Describe the bug**
Logo on top left showing blank instead of proper logo.

**To Reproduce**
1. Checkout develop branch
2. run `npm start`
3. see empty square on top left [NOK]

**Expected behavior**
Logo should render properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/12553063/75643271-74e22f80-5c79-11ea-8589-46f9196ae7a5.png)

**Comment by yousifalraheem** [comment]
Fixed
