### ISSUE TITLE
Updated design: Accordion

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#15]
### Design review March 27

The accordion has been updated. 

**Change**
- The green “tab border” is removed
- Font in header is 20 px, with the option of a sub header (14 px)
- Header cell height:  if header only 48 px, if sub header 64 px
- Grey hover is added on the header cell
- Content background is still white/none, with the option to make it grey
- Chevron (FontAwesome Light) points up/down (not right/down)
- Guidelines now include: "Use this component mainly for text content"

**Reason**
Many reasons. First of all, it was time to specify the component better. We have adjusted to fit users’ need with more efficient use of space. The direction of chevron is updated to show how it is animated. We also noticed that the component has been (too) content-heavy and added clearer guidelines. 

**Specification**
https://designlibrary.sebgroup.com/components/accordion/

![image](https://user-images.githubusercontent.com/45568194/57231453-cfd7d580-701a-11e9-89af-38ab4e9b15be.png)

Let us know if you have any questions!
/Ulrika
Design management

**Comment by ulde01** [comment]
Sorry if I have already added this issue - I thought I did but can't find any trace of it so maybe I messed up. Anyway, let me know how you are getting on.  You can find all the details here: https://designlibrary.sebgroup.com/components/accordion/#styles

**Comment by DanSallau** [comment]
@ulde01 , about the 5th option

> Content background is still white/none, with the option to make it grey

Considering the third option specify 

> Grey hover is added on the header cell

Wouldn't having a grey background conflict with the hover background then ? I mean if your background is already grey as mentioned in the 5th option, what color would the hover be to make it interactive as intended ?

**Comment by mario-subo** [comment]
I've gone through the list and made the following changes:
- [x] The green “tab border” is removed
- [x] Font in header is 20 px
- [x] with the option of a sub header (14 px)
- [x] Header cell height: if header only 48 px, if sub header 64 px
- [x] Grey hover is added on the header cell
- [x] Chevron (FontAwesome Light) 
- [x] Chevron points up/down (not right/down)
- [x] Guidelines now include: "Use this component mainly for text content"
- [x] Changed the border color to `grey8` as per specification

If I anyone notices I skipped anything or not implemented something correctly do let me know please.

I created a pull request #18 which closes this issue
