### ISSUE TITLE
Small input field (new component)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#179]
### Design decision 2020-03-18
![image](https://user-images.githubusercontent.com/45568194/77446976-6b1e9880-6def-11ea-8efe-6abd6c4f14ab.png)

**What is this?**
A smaller size of input fields.

**See all details here**
https://designlibrary.sebgroup.com/components/forms/input/#specification

**Reason**
A smaller size of input fields that can be used inside tables and lists.

If this issue is not relevant to you, please comment and close it.

Thank you! :)
/Ulrika

**Comment by yousifalraheem** [comment]
The width is fully customizable by the user of the TextBox component. Therefore, we don't need a separate component for this.
