### ISSUE TITLE
Table component unchecked all returns non-empty array

### ISSUE THREAD

**Issue by kherP** [sebgroup/react-components#182]
**Describe the bug**
When enabling the checkboxes in Table component, unchecking all the selections with the top most checkbox returns non-empty array.

**To Reproduce**
1. Set up Table component with `onRowSelected` with some console in it
2. Click on top most checkbox
3. All rows are selected, and all rows are returned in console
4. Click the top most checkbox again to uncheck all selections

**Expected behavior**
When uncheckinng all selections, empty array should be returned.

**Comment by DanSallau** [comment]
Fix by https://github.com/sebgroup/react-components/pull/186
