### ISSUE TITLE
Tooltip: the container should not be translucent

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/react-components#249]
**Describe the bug**
The tooltip container is currently translucent which it shouldn't be. There is no mention anywhere in the [Design Library Guidelines](https://designlibrary.sebgroup.com/patterns/feedback-to-the-user/guide-the-user/tooltip/#guidelines) of a tooltip container being translucent

**To Reproduce**
1. Run the docs
2. Visit Tooltip page
3. Scroll down to examples
4. Toggle the tooltip
6. Scroll the page where an item can come underneath it.
5. See the issue

**Expected behavior**
The tooltip container should be completely solid. No transparency is required.

**Screenshots**
<img width="348" alt="Screen Shot 2020-04-09 at 2 29 14 PM" src="https://user-images.githubusercontent.com/10633734/78864814-0742d380-7a6f-11ea-93d9-00de98cbb5e9.png">

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 10
 - Browser Chrome, Safari, Firefox, Edge, IE

**Comment by kherP** [comment]
.show style is inherited from sebgroup/bootstrap by default the opacity is 0.9
