### ISSUE TITLE
form components should update styles

### ISSUE THREAD

**Issue by mario-subo** [sebgroup/react-components#28]
**Describe the bug**
Some of the component styles do not match the specifications defined in SEB design library.

**Expected behavior**
- The label fonts should be 16px medium weight
- The default component height should be 44px
- default component border color should be grey6, blue on hover and dark blue when focused

**Comment by ulde01** [comment]
Hi, did this include height 44px for radio buttons and check boxes (of course also input field, drop down, medium button, segmented control and stepper)? If so I won't create a new issue for this, as I have done in the other repos. Keep it up and thank you! /U
