### ISSUE TITLE
Slider design (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#298]
### Design update 2020-04-17
**Change**
Have a look at the specification (link below) because the component has been redesigned in a few ways, but a couple of details are:
- No chevron
- Line: Height 4 px, rounded corners 
- Thumb size: 24 x 24 px
- Hover state: Thumb is enlarged
- Focus state: Thumb is framed

![Slider-2020-04-17](https://user-images.githubusercontent.com/45568194/79566170-64afd380-80b2-11ea-822b-cbb2baf7f35f.png)

**Details** 
https://designlibrary.sebgroup.com/components/slider/#specification

**Component identifier**
component-slider

As always, act on it if relevant, comment and close if not. :)
/Ulrika, Design management

**Comment by mario-subo** [comment]
@ulde01 So the input field on the right should always be displayed? Should we provide an option to hide it as well? Also should we display the tooltip when dragging like we did before? 
![image](https://user-images.githubusercontent.com/49055952/79729250-c88c0380-8321-11ea-9663-7d0668ed0476.png)

**Comment by JessiNygrenWalhed** [comment]
The input field should be optional, right? It depends on context I would say.
The tooltip should still be used. @ulde01 I can´t ping Leopold. Can you? Think this is a question for him? How is the "new" slider build?

**Comment by TheresaHedlund** [comment]
Agree with Jessi. If there are fixed steps in the slider, the value could be shown without the input field. The tooltip might also be optional, since it doesn't always add value.

**Comment by EldRoos** [comment]
Yes should be optional to have input field and tooltip. Also preferably tooltip should be formated with thousand divider and unit.
