### ISSUE TITLE
Table component 

### ISSUE THREAD

**Issue by DanSallau** [sebgroup/react-components#39]
### Table component description
- [x] Pagination
- [x] Filters
- [x] Search
- [x] Sort
- [x] Collapsable
- [ ] Direct data manipulation (editable fields)
- [ ] Different sizes (Normal, condensed, etc)
- [ ] Different themes (based on SEB's bootstrap)

**Comment by nileke** [comment]
react-rable v7 (https://github.com/tannerlinsley/react-table) could be an alternative as it give all the requested functionality and leave the styling to the developer. 

Hooks are needed for this.

**Comment by DanSallau** [comment]
@nileke i have experimented with this idea for few weeks now. Although i reckoned and recognised the robustness of react-table, i don't think we can achieve the flexibility we need. For example, combining . the grouping and the sorting feature seems to be a hassle and comes with limitations as a result. At this juncture, it is imperative on us to build our custom table that fit our requirement i believe however limited and this regard, i would be proceeding.
