### ISSUE TITLE
Table server sorting always sort with descending order

### ISSUE THREAD

**Issue by kherP** [sebgroup/react-components#390]
**Describe the bug**
When using server sorting function in table component, the header will not highlight the sorted column and is always returning `DESC` as the sort order.

**To Reproduce**
1. Define table with server sorting function
2. Set one of the header columns to isSorted = true and isSortedDesc = true
3. The header with isSorted = true is not highlighted [NOK]
4. Click the header again
5. Notice that the order direction return is still `DESC` instead of `ASC` [NOK]

**Expected behavior**
Header with isSorted = true should be highlighted. When using server sort, order direction can be Ascending or Descending.

**Screenshots**
https://stackblitz.com/edit/react-ts-yclund

**Additional context**

**Comment by DanSallau** [comment]
Fixed by https://github.com/sebgroup/react-components/pull/392
