### ISSUE TITLE
Overflowed item hidden/cut-off in multi-select dropdown

### ISSUE THREAD

**Issue by aurelius0523** [sebgroup/react-components#40]
**Describe the bug**
Overflowed items in multi-select dropdown is hidden/cut-off

**To Reproduce**
1. Go to https://sebgroup.github.io/react-components/#/dropdown
2. Enter all 5 items into 'multi-select' drop down

**Expected behavior**
The dropdown should expand to accomodate for all selected options, similar to:
https://semantic-ui.com/modules/dropdown.html

**Comment by yousifalraheem** [comment]
This is fixed and will be released soon
