### ISSUE TITLE
Breadcrumb breaks in IE

### ISSUE THREAD

**Issue by aurelius0523** [sebgroup/react-components#41]
**Describe the bug**
Breadcrumb items do not appear in one line in IE

**To Reproduce**
1. Open https://sebgroup.github.io/react-components/#/breadcrumb in IE
2. Look at Breadcrumb component

**Expected behavior**
All items in the breadcrumb should show in one line

**Additional context**
It seems that IE is unable to calculate the height of the resized chevron in ::before selector. Adding height property seems to be a working override. It only works if you change it in code. IE doesn't recalculate the height if you only modify the height in IE console

**Comment by hjalmers** [comment]
Hi @aurelius0523, this bug has been fixed in [this commit](https://github.com/sebgroup/bootstrap/commit/9ad7eb47d1da914a1751d77db1422267fc8b0119) and will be part of the next release of https://github.com/sebgroup/bootstrap which I hope to release before the end of this week:)
