### ISSUE TITLE
Button (etc) focus state - 4 px gradiant, Blue and Red (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#432]
**Change**

Focus state on interactive components (button, link, table row, logotype, etc) goes from a flat 3 px outline in "Dark Blue 2", to a gradient 4 px outline:

![image](https://user-images.githubusercontent.com/45568194/85997618-008e8180-ba0a-11ea-8678-c441931bbffa.png)

**Blue**
- Blue focus state is a gradient 4 px outline in seb-blue/#41B0EE:
- box-shadow: 0 0 4px 1px #41B0EE;

**Red**
- Red focus state is a gradient 4 px outline in seb-red/#F03529:
- box-shadow: 0 0 4px 1px $seb-red;

**Reason**
This time we focused on the focus state for blue and red buttons but the goal is to bring a consistency throughout our components and frameworks, so these colours could be applied on all interactive components.

Thank you!
/Ulrika

**Comment by yousifalraheem** [comment]
This should be fixed in Bootstrap and inherited in the components
