### ISSUE TITLE
Pagination prop 'size' description is confusing

### ISSUE THREAD

**Issue by AaronTee** [sebgroup/react-components#447]
**Describe the bug**
I have a table that has 18 pages in total (Math.ceil(rows.length / pageSize), 10 records to be displayed in one page and total of 171 records in data set.
```
<Pagination
    size={18} // maximum number of pages (from documentation)
    offset={5} // The number of items to be displayed per page (from documentation)
    ...
/>
```
I believe the size prop is for total number of data rows? In that case it is working fine but how can I limit the number of page items/buttons to show? and the prop size description need to change.

**Desktop (please complete the following information):**
 - OS: windows 10 x64
 - Browser: Chrome
 - Version 83.0.4103.97

**Comment by DanSallau** [comment]
Hi @AaronTee Sorry for the late reply. As for the number of page/Items button , i beleive the pagination exposed a property called `pagingLength` . I think that's what you need.

**Comment by mario-subo** [comment]
https://sebgroup.github.io/ng-components/docs/pagination

You can check the playground and the descriptions on our angular components as it follows the same API. The descriptions are a bit easier to understand. 

![image](https://user-images.githubusercontent.com/49055952/90481635-b0f44880-e164-11ea-8cfc-76e05c5e520d.png)

Thanks for raising an issue, we can change the name of the props moving forward to make it more understandable.
