### ISSUE TITLE
Grey background colour (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#489]
### Design decision 2020-10-21

**Change**
Change the grey background to #EEEEEE.

**Page in Design Library**
https://designlibrary.sebgroup.com/foundation/our-design/visual-identity/colours/

**Reasoning**
To increase the contrast. To synk background colour between shells and public web sites. 

If this issue is irrelevant to you, please comment and close. Thank you! :) 
/Ulrika

**Comment by yousifalraheem** [comment]
Once this is updated in Bootstrap it will be reflected in our components automatically
