### ISSUE TITLE
Link colour (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#490]
### Design decision 2020-10-28

**Change**
The blue link colour has been updated to #0062BC.

**Details**
https://designlibrary.sebgroup.com/foundation/our-design/visual-identity/colours/

**Reason**
To increase the contrast to work better on both white, grey and other coloured backgrounds. Also, to synk link colours between shells and public web sites.

If this issue is irrelevant to you, please comment and close. Thank you! :)
/Ulrika

**Comment by yousifalraheem** [comment]
Once this is updated in Bootstrap it will be reflected in our components automatically
