### ISSUE TITLE
Upgrade to React 17?

### ISSUE THREAD

**Issue by marcusenqvist** [sebgroup/react-components#526]
Hi!
Do you have any plans to upgrade the project to use react 17.x? I am currently developing a new mfe using React 17 (since they claim that from v.17 and forward React will be backwards compatible). As i understand it, there are no breaking changes when upgrading, but mixing v.17 with earlier versions of React (in imported node modules) results in an error without workarounds. 

Would be cool if a new version of the package could be released for v.17 and forward. :)

**Comment by mario-subo** [comment]
The latest beta release has been upgraded to React 17
