### ISSUE TITLE
Datepicker in beta.4 showing red border when value is null

### ISSUE THREAD

**Issue by kherP** [sebgroup/react-components#549]
**Describe the bug**
Datepicker is showing red border when value is null

**To Reproduce**
1. Define a datepicker with null value

**Expected behavior**
Datepicker should not show red border if its value is null

**Screenshots**
![image](https://user-images.githubusercontent.com/12553063/112092856-5d9f1880-8bd3-11eb-8dd3-bb11c1a71fa2.png)

**Comment by mario-subo** [comment]
fixed in re #557
