### ISSUE TITLE
button flickering when set to different theme

### ISSUE THREAD

**Issue by kherP** [sebgroup/react-components#552]
**Describe the bug**
button flickers when set to theme other than primary

**To Reproduce**
1. Define a button with theme other than primary
2. refresh the page
3. see flickering

**Expected behavior**
Button should not flicker on render

**Screenshots**

![button](https://user-images.githubusercontent.com/12553063/112611179-766c3000-8e58-11eb-9f4e-4a5da81641a1.gif)

**Comment by yousifalraheem** [comment]
fixed in #553
