### ISSUE TITLE
Brand and favicon for docs

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/react-components#619]
## Description
It has been discussed before that the components should have a name and a brand logo. It is an open-source project and it should not be called **"SEB React components"**. This should also reflects on the favicon which is currently Gatsby's favicon.

**Comment by mario-subo** [comment]
Thanks for picking up on the favicon, it should be SEB. Could you elaborate a bit more on the fact that we should call the components "SEB React component". I'm not really following.

**Comment by yousifalraheem** [comment]
Companies fund open source projects to help them build their own UI and also share it with the community. When it's done, it usually presented as a standalone product. Imagine if React is called "Facebook UI renderer", or Bootstrap called "Twitter's design library", or Backstage called "Spotify's internal tooling system", and so on.

Instead, each one of these has its own name, brand, logo, and so on. This subject has been discussed with the design library team and FrontX. The conclusion was, we should come up with name(s) and present it/them to FrontX. Once one has been selected, a logo is to be designed and used as well. When that's done, SEB will only be mentioned as a sponsor.
