### ISSUE TITLE
Table design (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/react-components#62]
### Component review 2019-10-08
There are two small and important changes on table design:
- Bigger table header font: 16 px, medium, Grey 2 (#333333)
- New sorting icon: Normal = Grey 7 (#B2B3B3), Selected= Dark Blue 2 (#007AC7), Hover = Blue (#41B0EE)
- The sorting icon is FontAwesome solid "chevron-up" and solid "chevron-down", on top of each other, width 10 x height 16 px (together)

![image](https://user-images.githubusercontent.com/45568194/66406622-373fea00-e9ec-11e9-9bcf-7d7d922fbe23.png)

There is more to come, but these changes are the most urgent. So the rest of what we know about tables stays the same for now.

Thank you!
/Ulrika
Design Management

**Comment by ulde01** [comment]
Status please? Thank you! /Ulrika

**Comment by DanSallau** [comment]
@ulde01 its coming along, we wanted to utilized a helper library from our discussion with @nileke here https://github.com/sebgroup/react-components/issues/39 . We realized building a component around it is not ideal and hence we are rewriting our own. It will a week or two at max. I will get back to you soon .

**Comment by ulde01** [comment]
Thank you! Just to let you know, we wanted to change more design on it but were not able to (time constraints). So this is only step one. Good luck! /U

**Comment by hjalmers** [comment]
You could use this as a base for the styling it works with and without bootstrap https://github.com/sebgroup/bootstrap/commit/8b54db6726aeb10ab2867a855b577e199c55e747

It will be part of next release which I hope I'll be able to push later today:)
