### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by iamwilson** [sebgroup/react-components#74]
Hi Spartans,

Just a feature suggestion with regards to the accordion component.

Often times when showing summary data, the accordion comes into play for condensing the data.

Could we have one accordion with a plus sign (+) default and minus (-) on collapse as props. Perhaps the float right or left could also be a prop.

Example - default
![image](https://user-images.githubusercontent.com/1440429/67176109-47e45d00-f3fb-11e9-82c3-b948fec1adda.png)

Example - collapsed
![image](https://user-images.githubusercontent.com/1440429/67176276-f9838e00-f3fb-11e9-9f44-6577ec627b2e.png)

**Comment by yousifalraheem** [comment]
We have this feature already

You can pass any custom icon and you have two icon positions, right and left

https://sebgroup.github.io/react-components/#/accordion
