### ISSUE TITLE
Textbox component 'reference' not passing down to input props.

### ISSUE THREAD

**Issue by AaronTee** [sebgroup/react-components#754]
**Describe the bug**
I've tried to pass reference to Textbox component but it is not working.

**To Reproduce**
1. Declare a const ref = createRef();
2. Pass into component <Textbox reference={ref} ... />
3. useEffect with ref.current as dependency, then console log ref. OR check from browser developer tool ('reference' spread to input props)

**Expected behavior**
Textbox reference props should be passing down to <input> ref props.

**Screenshots**
![image](https://user-images.githubusercontent.com/7609616/182295026-7e92cd36-288a-45e2-b36f-f9bf108d2382.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 102.0.5005.148 (Official Build) extended (64-bit)

**Comment by eweseong** [comment]
Hi @AaronTee, could you try to pass your ref in the `ref` props instead? We have setup ref forwarding so you should be able to pass reference as per usual, the `reference` prop seemed like an obsolete property, we will remove them in the next upcoming release.

```
<Textbox ref={ref} ... />
```

**Comment by AaronTee** [comment]
Passing ref works, thank you.
