### ISSUE TITLE
Slider startpoint

### ISSUE THREAD

**Issue by EldRoos** [sebgroup/react-components#85]
**Is your feature request related to a problem? Please describe.**
Be able to set where the blue bar should start from.

**Describe the solution you'd like**
A setting that tells where the midpoint is. If not set it default to min value.
Especially useful when using min values less than 0 and want to show the blue bar from 0. 

**Describe alternatives you've considered**
Still use default behavior from before.

**Additional context**
![SliderMid](https://user-images.githubusercontent.com/14058437/67771214-2d902c00-fa58-11e9-9e50-41a9a04b1bce.png)

Approved by: Ulrika Dettner-Larsson & Henrik Hoglund.

**Comment by yousifalraheem** [comment]
@EldRoos , @ulde01
Just to double check, this is sticky presentational. Meaning, the returned value is not a range between the start point and the selected value

**Comment by EldRoos** [comment]
Yea, only a visual change.

**Comment by EldRoos** [comment]
Nice.

Is it still possible to set the startpoint to be for example 500, if you have min 0 and max 1000 and want it to go from middle?

**Comment by EldRoos** [comment]
Also: finally got react-components to build. Looks like disabled slider have hover effect, it should not.
