### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by EldRoos** [sebgroup/react-components#86]
**Is your feature request related to a problem? Please describe.**
When comitting code you get a lot of changes in the changed files when using a beauitifier/prettier. Code should be formatted the same, not dependent of personal preference or just randomness.

**Describe the solution you'd like**
Everyone contributing to React Components should use Prettier extension to VS Code (or something equal to it) with same settings (rc file in the project).

**Describe alternatives you've considered**
Turning of auto formater when using React Components.

**Additional context**
Extension: Prettier - Code Formater v2.3.0

Using file: .prettierrc

A version similar to how many of you already writes:
```
{
    "arrowParens": "avoid",
    "bracketSpacing": true,
    "printWidth": 120,
    "semi": true,
    "singleQuote": false,
    "tabWidth": 4,
    "trailingComma": "es5"
}
```
Or more common version (less width, single quotes):
```
{
    "arrowParens": "avoid",
    "bracketSpacing": true,
    "printWidth": 80,
    "semi": true,
    "singleQuote": true,
    "tabWidth": 4,
    "trailingComma": "es5"
}
```

**Comment by yousifalraheem** [comment]
We do formatting before committing but we are using VSCode formatter not prettier, that's why when you run prettier you find a lot of changes appearing. However, I think we should set up prettier how we want it to look like and configure `precommit` to run prettier and add the changes so that the process is automatic. I'll tag this issue as an enhancement.

**Comment by EldRoos** [comment]
You are doing manual formatting? Or some automatic one? If it is automatic I don't think it is that good as for example sometimes use "..." and sometimes '...'.

What parts of formatting in https://github.com/sebgroup/react-components/pull/109/files did you not like? And think through if it is only your subjective view or if most think so.
For example I never start a line with +, I end them with it. Even when I didn't use a beautifier.
