### ISSUE TITLE
Tooltip misaligned and not able to close in mobile

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/react-components#89]
**Describe the bug**
When triggering a tooltip on mobile, tooltip message box is misaligned and not able to be closed.

**To Reproduce**
1. Go to 'Dashboard' using mobile
2. Click on the info icon
3. See the misalignment and the tooltip cannot be closed.

**Expected behavior**
Tooltip message should be able to view clearly and toggle to be hidden or to be seen

**Screenshots**
![801d2180-f030-11e9-9d7e-3577b573ac47](https://user-images.githubusercontent.com/10633734/68736572-edb27280-061b-11ea-9977-efbaab6e41f9.png)

**Comment by EldRoos** [comment]
We had this problem in our project too. Old iOS/Safari/Chrome do not trigger click on non button/inputs (newest version have fixed this). We also used "touchstart" to fix this.
