### ISSUE TITLE
Modal tabIndex is disrupting body normal tabIndex flow

### ISSUE THREAD

**Issue by yousifalraheem** [sebgroup/react-components#90]
**Describe the bug**
The modal component has a `tabIndex` set to `-1` for the `div` of class `modal`. This is preventing the normal tab flow of the content inside the modal

**To Reproduce**
1. Use the `Modal` component
2. In the body, use a `RadioGroup` component
3. Toggle the modal
4. Tab into the radio buttons using your keyboard
5. Try to change the value with arrows (default behavior)
6. See the error

**Expected behavior**
The values should be changed swiftly without being interrupted

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**
A workaround could be done by selecting the modal `div` element and running `modal.removeAttribute("tabIndex")`. This solves the issue.

### Additional minor fixes
Please try to add the following:
- Transition out animation
- Position center property

**Comment by EldRoos** [comment]
Maybe use a focus trap like Focus Lock:
https://github.com/theKashey/react-focus-lock

More info about focus traps:
https://hackernoon.com/its-a-focus-trap-699a04d66fb5
