### ISSUE TITLE
Toggles only show checkbox

### ISSUE THREAD

**Issue by EldRoos** [sebgroup/react-components#96]
**Describe the bug**
When we use React Components v2.1.1 we only get checkboxes instead of the toggles.

**To Reproduce**
1. Use this branch 'https://github.sebank.se/SEBHome/Loans.Mortgages.Portfolio.UI/tree/feature/components'
2. Install packages and start project.
3. Go to: 'http://localhost:6102/'
4. See error in lower part of window (in "Händelser i livet" section or "Händelser i livet" in the screenshots).

**Expected behavior**
Show a normal toggle button.

**Screenshots**
![Toggle1](https://user-images.githubusercontent.com/14058437/70235847-08cc5a00-1764-11ea-98e3-0f73d69ec6be.png)
![Toggle2](https://user-images.githubusercontent.com/14058437/70235848-0964f080-1764-11ea-8b06-241aa62a31f1.png)

**Devices:**
 - All

**Additional context**
Please try out and see if you could find any obvious error. Custom css for Toggles are turned off.

**Comment by mario-subo** [comment]
Seems like an issue with `parcel` you might need a plugin.

![image](https://user-images.githubusercontent.com/49055952/70293032-f06b4680-181a-11ea-8a70-972ceeb231a3.png)

**Comment by EldRoos** [comment]
When did you get that error? Building? Starting? Or running?
It worked well with react components v1 and parcel which also had typescript too.
I don't get that error that you showed.

**Comment by EldRoos** [comment]
Fixed by adding bootstrap, parcel optimized it away. Closed!
